# Build
FROM node:16-alpine as build
WORKDIR /frontend/
COPY ./package.json ./package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Run
FROM node:16-alpine
WORKDIR /frontend/
COPY --from=build /frontend/package.json /frontend/package-lock.json ./
ENV PATH /frontend/node_modules/.bin:$PATH
RUN npm install --only=production
COPY --from=build /frontend/.next ./.next
EXPOSE 3000
CMD ["npm", "run", "start"]